### PR TITLE
use more Slevomat sniffs

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Needs to wait for the next Slevomat-CS release. GH-80 is probably fixed with `SlevomatCodingStandard.PHP.OptimizedFunctionsWithoutUnpacking`

**Comment by mmoll** [comment]
this is ready for review now

**Comment by mmoll** [comment]
Added `SlevomatCodingStandard.ControlStructures.EarlyExit` and raised minimum `slevomat/coding-standard` version to `4.8.5`.

**Comment by mmoll** [comment]
@Ma27 I'm referring to the `ruleset.xml` comments in the README now, as it's IMHO way too tedious to duplicate this information now.

**Comment by Ma27** [comment]
this is a sensible solution as well IMHO. I only wanted to have somewhere in the README documented which rules (or where to find them) are used.

Let's wait for AppVeyor and then I'd merge this:)

**Pull request merged**
