### PR TITLE
backports to 2.x and 2.1.3 CHANGELOG

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
I think this would be nice to have for people who are still stuck on PHP <7.1.

**Comment by mmoll** [comment]
:green_heart: - we don't have `.appveyor.yml` in this branch.

**Comment by calbrecht** [comment]
:+1:

**Comment by xalopp** [comment]
How about to add the appveyor file?

**Comment by mmoll** [comment]
@xalopp How about now? :green_heart:

**Pull request merged**
