### PR TITLE
Version 10

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
@Khartir @valentin-schaeidt-mayflower could you check the Attributes rules in your respective project and report back if this fits your needs?

**Comment by Khartir** [comment]
Minor issue: sorting the attributes alphabetically includes a leading `\` in the order. This leads to `#[\Attribute]` always being the last attribute, but that's a negligible edge-case.

More importantly, I just had this happen:

```diff
    #[Bar()]
-    // TODO do something
    public function foo(): void
```

**Comment by mmoll** [comment]
Thanks, I opened https://github.com/slevomat/coding-standard/pull/1497.

**Comment by mmoll** [comment]
@Khartir Could you check again? :)

**Comment by Khartir** [comment]
It still does weird stuff:
```diff
 //phpcs:disable SlevomatCodingStandard.PHP.ForbiddenClasses
-#[Bar()] /** foo */
 class TestCase
```
But I think we can merge this and either fix it upstream or disable offending sniffs downstream.

**Pull request merged**
