### PR TITLE
use phpcs.xml.dist for scrutinizer

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
let's see where this is going, per https://scrutinizer-ci.com/docs/tools/php/code-sniffer/

**Comment by xalopp** [comment]
Maybe  overriding the step with `- phpcs-run --standard=phpcs.xml` will work?

**Comment by mmoll** [comment]
I wiped the whole phpcs defaults of Scrutinizer, now it seems good.

**Comment by xalopp** [comment]
Sure? For me the log for the phpcs-run still looks the same.  https://scrutinizer-ci.com/g/mayflower/mo4-coding-standard/inspections/84849830-413e-43b1-b9fd-13a175a7062e/log 

Maye adding an error the phpcs.xml.dist will point out this file is used or not.

**Comment by mmoll** [comment]
The "Patches" tab in the report is gone now and there are no generated "recommended" patches anymore.

**Comment by xalopp** [comment]
Ok, now I get it :man_facepalming:

**Pull request merged**
