### PR TITLE
clean up composer.json

### PR DESCRIPTION
**Pull request by xalopp**

### CODE REVIEW

**Comment by mmoll** [comment]
@xalopp While I'm not against raising the minimum to 7.x, isn't PHPUnit 6.x still supported per phpunit.de?

**Comment by xalopp** [comment]
@mmoll I would have kept `PHPUnit 6.x` but the newly introduced PHP 7.3 supports, which is  supported by `PHPUnit 7.x` and higher, motivated me to drop either the support for anything below `PHPUnit 7.x`.

Since this is a Development Requirement, it won't mess up with the dear MO4-Users.

**Comment by calbrecht** [comment]
Well then :+1

**Comment by mmoll** [comment]
I'm not against it, I'm just asking questions. :question:

**Comment by mmoll** [comment]
merged, merci @xalopp!

**Pull request merged**
